### ISSUE TITLE
error tried to attach full log but it wont let me

### ISSUE THREAD

**Issue by jpoblocki77** [bdew-wurm/fishbuddy#1]
[09:21:37 AM] SEVERE org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher: java.lang.NoClassDefFoundError: net/bdew/wurm/tools/server/bytecode/ByteCodeUtils
java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/bdew/wurm/tools/server/bytecode/ByteCodeUtils
	at net.bdew.wurm.fishy.FishyMod.preInit(FishyMod.java:155)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$6(ModLoaderShared.java:173)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:171)
	at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.Loader.run(Loader.java:286)
	at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at PatchedLauncher.main(PatchedLauncher.java:20)
Caused by: java.lang.NoClassDefFoundError: net/bdew/wurm/tools/server/bytecode/ByteCodeUtils
	at net.bdew.wurm.fishy.LoreActionPatch.apply(LoreActionPatch.java:25)
	at net.bdew.wurm.fishy.FishyMod.preInit(FishyMod.java:143)
	... 23 more
Caused by: java.lang.ClassNotFoundException: net.bdew.wurm.tools.server.bytecode.ByteCodeUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:3
[wurm server log.txt](https://github.com/bdew-wurm/fishbuddy/files/8043005/wurm.server.log.txt)
49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javassist.Loader.delegateToParent(Loader.java:431)
	at org.gotti.wurmunlimited.modloader.classhooks.HookManager$1.delegateToParent(HookManager.java:174)
	at javassist.Loader.loadClass(Loader.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

if you need the full log let me know and ill post it on pastebin

**Comment by jpoblocki77** [comment]
sorry i just realized i posted this in the wrong spot

**Comment by bdew** [comment]
I assume this is for https://github.com/bdew-wurm/fishytweaks
The error means it's missing a class from my server tools mod (https://github.com/bdew-wurm/bdew_server_mod_tools/releases)
Make sure you have the latest version of both mods, maybe try re-downloading them in case something got corrupted
If it still doesn't work open a bug in the right place or poke me on discord.
